IMSIZE = 64
DEVICE = "cuda"
DATA_PATH = "data/skins"
SAMPLE_DIR = "results/samples"
WEIGHTS_DIR = "results/weights"
SEED = 23
EVALUATION_INTERVAL = 1
USE_RAM = False
NUM_WORKERS = 4
MIXED_PRECISION = True

TRAIN_BATCH_SIZE = 240
EVAL_BATCH_SIZE = 10
LR = 0.0002
NUM_TRAIN_TIMESTEPS = 1000
EPOCHS = 100
