IMSIZE = 64
DEVICE = "cuda"
DATA_PATH = "data/album_covers_512/"
SAMPLE_DIR = "results/samples"
WEIGHTS_DIR = "results/weights"
SEED = 23
EVALUATION_INTERVAL = 10
USE_RAM = True
NUM_WORKERS = 8
MIXED_PRECISION = False

TRAIN_BATCH_SIZE = 640
EVAL_BATCH_SIZE = 64
LR = 0.0001
NUM_TRAIN_TIMESTEPS = 1000
EPOCHS = 10000
